#!/bin/bash
#
# This script creates a db backup and generates a gz file
# for redmine and geppetto
#
# To generate a crontab for it you can type something like:
# crontab -e
# 0 2 * * * /home/ec2-user/redmine/script/databaseBackup
# crontab -l

/usr/bin/mysqldump -u redmine -p[substitute_with_db_password] redmine | gzip > /home/ec2-user/osbDBBackup/redmine_`date +%y_%m_%d`.gz
/usr/bin/mysqldump -u geppetto -p[substitute_with_db_password] geppetto | gzip > /home/ec2-user/osbDBBackup/geppetto_`date +%y_%m_%d`.gz
