#!/bin/bash
#
# This script creates a db backup and generates a gz file
#
# To generate a crontab for it you can type something like:
# crontab -e
# 0 2 * * * /home/ec2-user/redmine/script/filesBackup
# crontab -l

cd /home/ec2-user/redmine/files/
tar -cvzf /home/ec2-user/osbDBBackup/redmineFiles.tar.gz * 